### PR TITLE
Bump @actions/core to 1.10.0

### PR DESCRIPTION
**Pull request by jsoref**
The equivalent of https://github.com/actions/upload-artifact/issues/353

### CODE REVIEW

**Comment by eine** [comment]
Duplicate of #178?

**Comment by mmkal** [comment]
For impatient people: we can use @jsoref's fork while we wait for GitHub to have a meeting about a meeting about whether to click "Merge":

```diff
-      - uses: actions/download-artifact@v3
+      - uses: jsoref/actions-download-artifact@e8e28081281db717c387052cf471367873957e46
```

At least, this worked for my team anyway. Thank you @jsoref!!

**Comment by amorujao** [comment]
#178 has been merged, so this one can be closed.

**Comment by konradpabjan** [comment]
Closing this out now that https://github.com/actions/download-artifact/pull/178 went in. Contributor PR were causing some CI to fail so I went ahead and took care of the changes

Thank you though for initially opening this up

**Pull request closed without merging**
