### PR TITLE
Update @actions/artifact to version 0.6.0

### PR DESCRIPTION
**Pull request by konradpabjan**
Update `@actions/artifact` to version `0.6.0` from version `0.5.2` and run `npm run release` to update `dist/index.js` with the latest changes

### CODE REVIEW

**Review by robherley — APPROVED** [review]
👍

**Review by 7atem328 — COMMENTED** [review]
[Code scanning - action](https://github.com/actions/download-artifact/actions/workflows/codeql-analysis.yml)

**Comment by Kenimartonia** [comment]
OK thank you

**Review by overtairdrop83 — COMMENTED** [review]
Work is going wel

**Comment by overtairdrop83** [comment]
Keep it up

**Pull request merged**
