### PR TITLE
feat: Add support for #143 - add ability to skip extracting a compressed artifact

### PR DESCRIPTION
**Pull request by austinsasko**
Adding a flag that will skip the gzip decode step

### CODE REVIEW

**Comment by Shutch748** [comment]
@Shutch748

**Review by Cowtail1 — APPROVED** [review]

**Comment by mandar1jn** [comment]
I'd love to see this added

**Comment by austinsasko** [comment]
After testing quite a bit I am unable to reproduce the original issue. It seems the underlying references no longer extract the artifact on download by default. If anyone sees a different behavior (the original one), please let me know here and ill see if I can repro and push the fix I had ready. Apologies for the delay

**Comment by nghhoese** [comment]
It still unzips by default would like to see a option to skip the unzipping process

**Pull request closed without merging**
